In [10]:
import pandas as pd
import os

In [11]:
from util.repo_paths import REPO_ROOT, DATA
path = str(REPO_ROOT / "data")
os.chdir(path)

data_path = path + "/brands/items/"

df_boj = pd.read_csv(DATA / "brands" / "items" / "beauty_of_joseon_skin_type.csv",index_col=False)
df_boj

                                       제품명           피부 타입
0      Calming Serum Green Tea + Panthenol       Sensitive
1              Glow Replenishing Rice Milk       Sensitive
2                  Radiance Cleansing Balm       Sensitive
3   Green Plum Refreshing Toner: AHA + BHA            Oily
4                       Red Bean Water Gel            Oily
5        Glow Serum Propolis + Niacinamide     Combination
6            Red Bean Refreshing Pore Mask     Combination
7          Ground Rice and Honey Glow Mask     Combination
8                            Dynasty Cream             Dry
9                    Ginseng Cleansing Oil  All Skin Types
10          Glow Deep Serum Rice + Arbutin       Sensitive
11          Green Plum Refreshing Cleanser       Sensitive
12             Apricot Blossom Peeling Gel             Dry
13       Light On Serum: Centella + Vita C       Sensitive
14                   Ginseng Essence Water             Dry
15             Hanbang Serum Discovery Kit  All Skin Types
16                 Ginseng Moist Sun Serum  All Skin Types
17      Matte Sun Stick: Mugwort + Camelia            Oily
18      Revive Eye Serum Ginseng + Retinal  All Skin Types
19      Revive Serum Ginseng + Snail Mucin  All Skin Types
20          Centella Asiatica Calming Mask       Sensitive

In [ ]:
#beauty of joseon
# 성별:
# Female : 75.74%
# Male : 24.26%
# 피부 타입:

# 연령대:
# 18-24 : 19.79%
# 25-34 : 34.57%
# 35-44 : 16.82%
# 45-54 : 13.28%
# 55+ : 15.54%


# dr.jart
# 연령대:
# 18-24세: 약 13.2%
# 25-34세: 약 36.77%
# 35-44세: 약 15.44%
# 45-54세: 약 14.54%
# 55세 이상: 약 20.05%
# 피부 타입:
# 민감성 피부: 약 40%
# 건성 피부: 약 30%
# 복합성 피부: 약 20%
# 지성 피부: 약 10%
# 성별:
# 여성: 약 80%
# 남성: 약 20%


# im from
# 연령대:
# 10대	2.50%
# 20대	42.94%
# 30대	44.46%
# 40대 이상	10.10%
# 피부타입:
# 복합	30.73
# 건성	15.77
# 지성	9.20
# 중성	3.80
# 민감성 :40.50
# 성별:
# 여성:	93.06
# 남성:	6.94			

# COSRX
# 연령대
# -18~24세: 약 18.39%
# -25~34세: 약 33.02%
# -35~44세: 약 17.22%
# -45~54세: 약 13.19%
# -55세 이상: 약 18.18%
# 성별
# -여성: 65.59%
# -남성: 34.41%
# 피부 타입
# -민감성 피부: 약 20~25%
# -지성 및 여드름 피부: 약 15~20%
# -복합성 피부: 약 25~30%
# -건성 피부: 약 30~35%


# purito
# Female: 83.88%
# Male: 16.12%
# 연령대:
# -18~24세: 약 17.87%
# -25~34세: 약 38.55%
# -35~44세: 약 14.12%
# -45~54세: 약 11.66%
# -55세 이상: 약 17.80%

In [14]:
amazon_df = pd.read_csv('amazon_df(ver_2).csv',index_col=False)

In [19]:
amazon_df['brand'].value_counts()

brand
COSRX               5189
PURITO              2388
I'm from            1779
Dr.Jart+            1771
Beauty of Joseon    1670
Name: count, dtype: int64

In [22]:
import random

brand_info = {
    'Beauty of Joseon': {
        'age_groups': ['18-24', '25-34', '35-44', '45-54', '55+'],
        'age_group_probs': [19.79, 34.57, 16.82, 13.28, 15.54],
        'gender_probs': {'Female': 75.74, 'Male': 24.26},
    },
    'Dr.Jart+': {
        'age_groups': ['18-24', '25-34', '35-44', '45-54', '55+'],
        'age_group_probs': [13.2, 36.77, 15.44, 14.54, 20.05],
        'gender_probs': {'Female': 80, 'Male': 20},
    },

    "I'm from": {
        'age_groups': ['10', '20', '30', '40+'],
        'age_group_probs': [2.50, 42.94, 44.46, 10.10],
        'gender_probs': {'Female': 93.06, 'Male': 6.94},
    },
    'COSRX': {
        'age_groups': ['18-24', '25-34', '35-44', '45-54', '55+'],
        'age_group_probs': [18.39, 33.02, 17.22, 13.19, 18.18],
        'gender_probs': {'Female': 65.59, 'Male': 34.41},
    },
    'PURITO': {
        'age_groups': ['18-24', '25-34', '35-44', '45-54', '55+'],
        'age_group_probs': [17.87, 38.55, 14.12, 11.66, 17.80],
        'gender_probs': {'Female': 83.88, 'Male': 16.12},
    }
}


def assign_age_and_gender(brand, brand_info):
    # 브랜드의 나이대와 성별 확률을 가져옵니다.
    age_groups = brand_info[brand]['age_groups']
    age_group_probs = brand_info[brand]['age_group_probs']
    gender_probs = brand_info[brand]['gender_probs']
    
    # 나이대 랜덤 선택
    age_group = random.choices(age_groups, weights=age_group_probs)[0]
    
    # 성별 랜덤 선택
    gender = random.choices(list(gender_probs.keys()), weights=gender_probs.values())[0]
    
    return age_group, gender

In [23]:
# amazon_df의 브랜드 열을 기준으로 나이대와 성별을 추가합니다.
amazon_df['age_group'] = amazon_df['brand'].apply(lambda x: assign_age_and_gender(x, brand_info)[0])
amazon_df['gender'] = amazon_df['brand'].apply(lambda x: assign_age_and_gender(x, brand_info)[1])

# 결과 확인
amazon_df.head()

,ASIN,title,order,Amazon_Category,brand,price,global_rating_count,Special_Feature,total_star_mean,Benefits,...,detected_language,Ingredients,Manufacturer recommended age,Date First Available,Batteries,Department,Package Dimensions,is_bundle,age_group,gender
0,B07DR5816K,Dr.Jart+ Cicapair Tiger Grass Color Correcting...,1,Makeup,Dr.Jart+,54.0,3367,Redness relief,4.2,"Right after using, 92% said skin looked less r...",...,en,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-24,Female
1,B07DR5816K,Dr.Jart+ Cicapair Tiger Grass Color Correcting...,1,Makeup,Dr.Jart+,54.0,3367,Redness relief,4.2,"Right after using, 92% said skin looked less r...",...,en,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35-44,Female
2,B07DR5816K,Dr.Jart+ Cicapair Tiger Grass Color Correcting...,1,Makeup,Dr.Jart+,54.0,3367,Redness relief,4.2,"Right after using, 92% said skin looked less r...",...,en,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55+,Male
3,B07DR5816K,Dr.Jart+ Cicapair Tiger Grass Color Correcting...,1,Makeup,Dr.Jart+,54.0,3367,Redness relief,4.2,"Right after using, 92% said skin looked less r...",...,en,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45-54,Female
4,B07DR5816K,Dr.Jart+ Cicapair Tiger Grass Color Correcting...,1,Makeup,Dr.Jart+,54.0,3367,Redness relief,4.2,"Right after using, 92% said skin looked less r...",...,en,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25-34,Female

In [24]:
states_population_percentage = {
"AK": 0.3,"AL": 1.5,"AR": 1.2,"AZ": 2.2,"CO": 1.7,"CT": 1.1,
"DC": 0.2,"DE": 0.3,"FL": 6.5,"GA": 3.2,"HI": 0.4,"IA": 1.0,
"ID": 0.6,"IL": 3.9,"IN": 2.1,"KS": 1.0,"KY": 1.6,"LA": 1.3,
"MA": 2.0,"MD": 1.9,"ME": 0.4,"MI": 3.6,"MN": 1.8,"MO": 2.2,
"MS": 1.1,"MT": 0.3,"NC": 3.2,"ND": 0.2,"NE": 0.9,"NH": 0.4,
"NJ": 2.8,"NM": 0.9,"NV": 1.0,"NY": 6.1,"OH": 3.5,"OK": 1.3,
"OR": 1.3,"PA": 4.1,"RI": 0.3,"SC": 2.0,"SD": 0.3,"TN": 2.2,
"TX": 8.7,"UT": 1.0,"VA": 2.5,"VT": 0.1,"WA": 2.3,"WI": 2.3,
"WV": 0.6,"WY": 0.1}

# 주와 비율을 별도로 리스트로 변환
states = list(states_population_percentage.keys())
percentages = list(states_population_percentage.values())

# amazon_df에 랜덤으로 주소 추가
amazon_df['address'] = random.choices(states, weights=percentages, k=len(amazon_df))

# 결과 확인
amazon_df.head()

,ASIN,title,order,Amazon_Category,brand,price,global_rating_count,Special_Feature,total_star_mean,Benefits,...,Ingredients,Manufacturer recommended age,Date First Available,Batteries,Department,Package Dimensions,is_bundle,age_group,gender,address
0,B07DR5816K,Dr.Jart+ Cicapair Tiger Grass Color Correcting...,1,Makeup,Dr.Jart+,54.0,3367,Redness relief,4.2,"Right after using, 92% said skin looked less r...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-24,Female,OH
1,B07DR5816K,Dr.Jart+ Cicapair Tiger Grass Color Correcting...,1,Makeup,Dr.Jart+,54.0,3367,Redness relief,4.2,"Right after using, 92% said skin looked less r...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35-44,Female,TX
2,B07DR5816K,Dr.Jart+ Cicapair Tiger Grass Color Correcting...,1,Makeup,Dr.Jart+,54.0,3367,Redness relief,4.2,"Right after using, 92% said skin looked less r...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55+,Male,WV
3,B07DR5816K,Dr.Jart+ Cicapair Tiger Grass Color Correcting...,1,Makeup,Dr.Jart+,54.0,3367,Redness relief,4.2,"Right after using, 92% said skin looked less r...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45-54,Female,NY
4,B07DR5816K,Dr.Jart+ Cicapair Tiger Grass Color Correcting...,1,Makeup,Dr.Jart+,54.0,3367,Redness relief,4.2,"Right after using, 92% said skin looked less r...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25-34,Female,ME